require:
  - rubocop-rspec
  - rubocop-rails

Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'spec/**/*'
    - 'db/**/*'

Layout/FirstHashElementIndentation:
  Exclude:
    - 'spec/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Rspec/ExampleLength:
  Max: 20

